stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build

deploy-job:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up --build -d